// Code generated by MockGen. DO NOT EDIT.
// Source: ../db/repository.go
//
// Generated by this command:
//
//	mockgen -source=../db/repository.go -destination=repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	repository "github.com/aifedorov/gophermart/internal/order/repository/db"
	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateTopUpOrder mocks base method.
func (m *MockRepository) CreateTopUpOrder(userID, orderNumber string) (repository.Order, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopUpOrder", userID, orderNumber)
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateTopUpOrder indicates an expected call of CreateTopUpOrder.
func (mr *MockRepositoryMockRecorder) CreateTopUpOrder(userID, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopUpOrder", reflect.TypeOf((*MockRepository)(nil).CreateTopUpOrder), userID, orderNumber)
}

// CreateWithdrawalOrder mocks base method.
func (m *MockRepository) CreateWithdrawalOrder(userID, orderNumber string, amount decimal.Decimal) (repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithdrawalOrder", userID, orderNumber, amount)
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithdrawalOrder indicates an expected call of CreateWithdrawalOrder.
func (mr *MockRepositoryMockRecorder) CreateWithdrawalOrder(userID, orderNumber, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithdrawalOrder", reflect.TypeOf((*MockRepository)(nil).CreateWithdrawalOrder), userID, orderNumber, amount)
}

// GetNewTopUpOrder mocks base method.
func (m *MockRepository) GetNewTopUpOrder() (repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNewTopUpOrder")
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNewTopUpOrder indicates an expected call of GetNewTopUpOrder.
func (mr *MockRepositoryMockRecorder) GetNewTopUpOrder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNewTopUpOrder", reflect.TypeOf((*MockRepository)(nil).GetNewTopUpOrder))
}

// GetOrderByNumber mocks base method.
func (m *MockRepository) GetOrderByNumber(number string) (repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByNumber", number)
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByNumber indicates an expected call of GetOrderByNumber.
func (mr *MockRepositoryMockRecorder) GetOrderByNumber(number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByNumber", reflect.TypeOf((*MockRepository)(nil).GetOrderByNumber), number)
}

// GetOrdersByUserID mocks base method.
func (m *MockRepository) GetOrdersByUserID(userID string) ([]repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByUserID", userID)
	ret0, _ := ret[0].([]repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByUserID indicates an expected call of GetOrdersByUserID.
func (mr *MockRepositoryMockRecorder) GetOrdersByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByUserID", reflect.TypeOf((*MockRepository)(nil).GetOrdersByUserID), userID)
}

// GetUserBalanceByUserID mocks base method.
func (m *MockRepository) GetUserBalanceByUserID(userID string) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBalanceByUserID", userID)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBalanceByUserID indicates an expected call of GetUserBalanceByUserID.
func (mr *MockRepositoryMockRecorder) GetUserBalanceByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBalanceByUserID", reflect.TypeOf((*MockRepository)(nil).GetUserBalanceByUserID), userID)
}

// GetUserWithdrawByUserID mocks base method.
func (m *MockRepository) GetUserWithdrawByUserID(userID string) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWithdrawByUserID", userID)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWithdrawByUserID indicates an expected call of GetUserWithdrawByUserID.
func (mr *MockRepositoryMockRecorder) GetUserWithdrawByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWithdrawByUserID", reflect.TypeOf((*MockRepository)(nil).GetUserWithdrawByUserID), userID)
}

// GetWithdrawalsByUserID mocks base method.
func (m *MockRepository) GetWithdrawalsByUserID(userID string) ([]repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawalsByUserID", userID)
	ret0, _ := ret[0].([]repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawalsByUserID indicates an expected call of GetWithdrawalsByUserID.
func (mr *MockRepositoryMockRecorder) GetWithdrawalsByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawalsByUserID", reflect.TypeOf((*MockRepository)(nil).GetWithdrawalsByUserID), userID)
}

// UpdateOrderStatusByNumber mocks base method.
func (m *MockRepository) UpdateOrderStatusByNumber(number string, status repository.Orderstatus, amount *decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatusByNumber", number, status, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatusByNumber indicates an expected call of UpdateOrderStatusByNumber.
func (mr *MockRepositoryMockRecorder) UpdateOrderStatusByNumber(number, status, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatusByNumber", reflect.TypeOf((*MockRepository)(nil).UpdateOrderStatusByNumber), number, status, amount)
}
