services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: gophermart
      POSTGRES_USER: gophermart
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U gophermart -d gophermart" ]
      interval: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://gophermart:password@postgres:5432/gophermart?sslmode=disable", "up" ]
    depends_on:
      postgres:
        condition: service_healthy

  app:
    build: .
    environment:
      DATABASE_URI: "postgres://gophermart:password@postgres:5432/gophermart?sslmode=disable"
      RUN_ADDRESS: "0.0.0.0:8080"
      SECRET_KEY: "my-secret-key"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - migrate