DROP INDEX IF EXISTS idx_users_username;
DROP TABLE IF EXISTS users;

DROP INDEX IF EXISTS idx_orders_number;
DROP TABLE IF EXISTS orders;

DROP TYPE IF EXISTS OrderType;
DROP TYPE IF EXISTS OrderStatus;